import { expect, test } from "@playwright/test";
const rows = 100_000;
test("sort perf: 100k × 20 two-key permutation", async ({ page }) => {
  await page.goto("/"); await page.getByRole("button", { name: "Load 100k×20" }).click(); await page.waitForSelector("text=/Loaded 100,000×20/", { timeout: 300_000 });
  const run = (kind: "sort" | "undo" | "redo") => page.evaluate(async kind => { const w=window as unknown as {__api:{applyOperations(v:object):Promise<unknown>;undo():void;redo():void};__workbookId:string;__sheetId:string}; if(kind==="undo") return w.__api.undo(); if(kind==="redo") return w.__api.redo(); return w.__api.applyOperations({workbookId:w.__workbookId,sheetId:w.__sheetId,atomic:true,operations:[{type:"range.sort",spec:{range:{startRow:0,startCol:0,endRow:99_999,endCol:19},hasHeader:false,keys:[{columnOffset:1,direction:"asc"},{columnOffset:0,direction:"desc"}]}}]}); }, kind);
  const now=()=>page.evaluate(()=>performance.now()); let t=await now(); await run("sort"); await expect.poll(()=>page.evaluate(()=> (window as unknown as {__api:{getWorksheetView(id:string):{getCell(r:number,c:number):{value:unknown}|undefined}};__sheetId:string}).__api.getWorksheetView((window as unknown as {__sheetId:string}).__sheetId).getCell(0,1)?.value)).toBe(0); const sortMs=(await now())-t;
  t=await now(); await run("undo"); await expect.poll(()=>page.evaluate(()=> (window as unknown as {__api:{getWorksheetView(id:string):{getCell(r:number,c:number):{value:unknown}|undefined}};__sheetId:string}).__api.getWorksheetView((window as unknown as {__sheetId:string}).__sheetId).getCell(0,1)?.value)).toBe(17); const undoMs=(await now())-t;
  t=await now(); await run("redo"); await expect.poll(()=>page.evaluate(()=> (window as unknown as {__api:{getWorksheetView(id:string):{getCell(r:number,c:number):{value:unknown}|undefined}};__sheetId:string}).__api.getWorksheetView((window as unknown as {__sheetId:string}).__sheetId).getCell(0,1)?.value)).toBe(0); const redoMs=(await now())-t;
  await page.waitForTimeout(700); await page.evaluate(()=>{(window as unknown as {__frameStats:{paintMs:number}[]}).__frameStats=[]}); const grid=page.locator("[data-testid=sheet-grid]"); for(let i=0;i<130;i+=1){await grid.dispatchEvent("wheel",{deltaY:200});await page.waitForTimeout(40)} const paints=await page.evaluate(()=> (window as unknown as {__frameStats:{paintMs:number}[]}).__frameStats.slice(10).map(x=>x.paintMs).sort((a,b)=>a-b)); const p95=paints[Math.floor(paints.length*.95)]??0;
  console.log(JSON.stringify({sortMs,undoMs,redoMs,p95,samples:paints.length})); expect(sortMs).toBeLessThanOrEqual(2000); expect(undoMs).toBeLessThanOrEqual(1500); expect(redoMs).toBeLessThanOrEqual(1500); expect(p95).toBeLessThanOrEqual(25);
});
