import { describe, expect, it } from "vitest";
import { findCells } from "../find-engine.js";
import { createOpenSheet } from "../create-opensheet.js";
import type { WorksheetView } from "@opensheet/core";
const sheet = (cells: Record<string, { value: any; formula?: string }>): WorksheetView => ({ id:"s",name:"s",rowCount:10,columnCount:10,frozenRows:0,frozenColumns:0,cellCount:Object.keys(cells).length,filter:null,getCell:(r,c)=>cells[`${r}:${c}`],*cellEntries(){for(const [key,data] of Object.entries(cells)){const [row,col]=key.split(":").map(Number);yield [row!,col!,data] as any;}},getRowHeight:()=>undefined,getColumnWidth:()=>undefined,forEachCellInRange:()=>{} } as WorksheetView);
const options = { query:"a",matchCase:false,wholeCell:false,searchIn:"values" as const,direction:"forward" as const };
describe("findCells",()=>{
 it("uses sparse deterministic row-major traversal and text matching",()=>expect(findCells(sheet({"2:1":{value:"Alpha"},"0:2":{value:"beta"},"0:1":{value:"A"}}),options)).toEqual([{row:0,col:1},{row:0,col:2},{row:2,col:1}]));
 it("distinguishes computed values from formula sources",()=>{const s=sheet({"0:0":{value:20,formula:"=SUM(A1:A2)"}});expect(findCells(s,{...options,query:"20",wholeCell:true})).toEqual([{row:0,col:0}]);expect(findCells(s,{...options,query:"sum",searchIn:"formulas"})).toEqual([{row:0,col:0}]);});
 it("formats booleans, errors, and reverse row-major order",()=>{const s=sheet({"0:0":{value:true},"1:0":{value:{type:"#REF!"}},"2:0":{value:true}});expect(findCells(s,{...options,query:"true",direction:"backward"})).toEqual([{row:2,col:0},{row:0,col:0}]);expect(findCells(s,{...options,query:"#ref!"})).toEqual([{row:1,col:0}]);});
 it("honors matchCase, wholeCell, and row inclusion",()=>{const s=sheet({"0:0":{value:"Alpha"},"1:0":{value:"foobar"}});expect(findCells(s,{...options,query:"alpha",matchCase:true})).toEqual([]);expect(findCells(s,{...options,query:"foo"})).toEqual([{row:1,col:0}]);expect(findCells(s,{...options,query:"foo",wholeCell:true})).toEqual([]);expect(findCells(s,{...options,query:"a"},row=>row===0)).toEqual([{row:0,col:0}]);});
});

describe("runtime findCells",()=>{
 it("searches all rows or only physical rows visible through a filter",async()=>{const api=createOpenSheet();const wb=api.createWorkbook({name:"find"});const id=wb.activeSheetId;await api.applyOperations({workbookId:wb.id,sheetId:id,atomic:true,operations:[{type:"range.write",range:"A1:A3",values:[["keep"],["hide"],["keep"]]},{type:"filter.apply",spec:{range:{startRow:0,startCol:0,endRow:2,endCol:0},hasHeader:false,conditions:[{columnOffset:0,operator:"equals",value:"keep"}]}}]});const base={sheetId:id,query:"hide",matchCase:true,wholeCell:true,searchIn:"values" as const,direction:"forward" as const};expect(api.findCells({...base,scope:"all"})).toEqual([{row:1,col:0}]);expect(api.findCells({...base,scope:"visible"})).toEqual([]);});
 it("validates public options and keeps compatibility calls unbound",()=>{const api=createOpenSheet();const wb=api.createWorkbook({name:"find"});expect(()=>api.findCells({sheetId:wb.activeSheetId,query:"",matchCase:true,wholeCell:false,searchIn:"values",scope:"all",direction:"forward"})).toThrow(/query/);const search=api.searchCells;expect(search({sheetId:wb.activeSheetId,query:"x",mode:"contains"})).toEqual([]);});
 it("findNext is strict, wraps, and validates anchors",async()=>{const api=createOpenSheet();const wb=api.createWorkbook({name:"find"});const id=wb.activeSheetId;await api.applyOperations({workbookId:wb.id,sheetId:id,atomic:true,operations:[{type:"range.write",range:"A1:C2",values:[["x","no","x"],["x",null,null]]}]});const base={sheetId:id,query:"x",matchCase:true,wholeCell:true,searchIn:"values" as const,scope:"all" as const,direction:"forward" as const};expect(api.findNext(base)).toEqual({row:0,col:0});expect(api.findNext({...base,from:{row:0,col:0}})).toEqual({row:0,col:2});expect(api.findNext({...base,from:{row:1,col:0}})).toEqual({row:0,col:0});expect(api.findNext({...base,direction:"backward"})).toEqual({row:1,col:0});expect(api.findNext({...base,direction:"backward",from:{row:0,col:0}})).toEqual({row:1,col:0});expect(api.findNext({...base,query:"missing"})).toBeNull();expect(()=>api.findNext({...base,from:{row:-1,col:0}})).toThrow(/from/);expect(()=>api.findNext({...base,from:{row:1000,col:0}})).toThrow(/outside/);});
 it("findNext wraps a single match to itself",async()=>{const api=createOpenSheet();const wb=api.createWorkbook({name:"find"});const id=wb.activeSheetId;await api.applyOperations({workbookId:wb.id,sheetId:id,atomic:true,operations:[{type:"cell.set",range:"B2",value:"only"}]});const base={sheetId:id,query:"only",matchCase:true,wholeCell:true,searchIn:"values" as const,scope:"all" as const,from:{row:1,col:1}};expect(api.findNext({...base,direction:"forward"})).toEqual(base.from);expect(api.findNext({...base,direction:"backward"})).toEqual(base.from);});
});
